version: "2"
services:
  order:
    build:
        context: ./order-api
        dockerfile: order-api.Dockerfile
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
        PORT: 3000
        MONGO_URL: mongodb://mongo/order
  payment:
    build:
        context: ./payment-api
        dockerfile: payment-api.Dockerfile
    ports:
        - "3001:3001"
    environment: 
        PORT: 3001
  mongo:
    image: mongo
    volumes:
      - /data/mongodb/db:/data/db
    ports:
      - "27017:27017"